# Generated by Django 3.0.6 on 2021-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
