# Generated by Django 3.1.5 on 2021-03-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20210316_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='acount_balance',
            new_name='account_balance',
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='location',
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
