# Generated by Django 3.0.6 on 2021-03-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20210320_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_input',
            name='source_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='source', to='travel.Destination'),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='dest_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dest', to='travel.Destination'),
        ),
    ]
