# Generated by Django 3.0.6 on 2021-03-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20210326_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place_image',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='place_image',
            name='image_id',
        ),
    ]
