# Generated by Django 3.0.6 on 2021-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20210327_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_hotel',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='type_of_Place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='place_image',
            name='image_of_place',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='transport',
            name='trans_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='trip_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='visit_place_type',
            field=models.CharField(max_length=50),
        ),
    ]
