# Generated by Django 3.0.6 on 2021-04-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20210328_2141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itinerary',
            unique_together={('trip_id', 'arrival_DnT')},
        ),
    ]
