# Generated by Django 3.1.7 on 2021-04-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20210403_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='type_of_room',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_hotel',
            field=models.ImageField(upload_to=''),
        ),
    ]
