# Generated by Django 3.0.6 on 2021-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20210405_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
