# Generated by Django 3.0.6 on 2021-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_hotel_hotel_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
