# Generated by Django 3.0.6 on 2021-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_auto_20210406_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_booking',
            name='ending_date',
            field=models.DateField(default='1111-1-1'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hotel_booking',
            unique_together=set(),
        ),
    ]
