# Generated by Django 3.0.6 on 2021-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_auto_20210407_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_booking',
            name='ending_date',
            field=models.DateField(default='1111-1-1'),
            preserve_default=False,
        ),
    ]
