# Generated by Django 3.0.6 on 2021-04-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_hotel_booking_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_booking',
            name='trip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='travel.User_Input', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hotel_booking',
            unique_together=set(),
        ),
    ]
