# Generated by Django 3.0.6 on 2021-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_auto_20210407_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_booking',
            name='payment',
            field=models.CharField(default='Remain', max_length=6),
            preserve_default=False,
        ),
    ]
