# Generated by Django 3.1.7 on 2021-05-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20210326_2128'),
        ('travel', '0019_hotel_booking_payment'),
    ]

    operations = [
    ]
