# Generated by Django 3.0.6 on 2021-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_merge_20210504_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='transport',
            name='place_hold_once_sd',
        ),
        migrations.AlterUniqueTogether(
            name='transport_booking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transport_booking',
            name='trans_id',
        ),
        migrations.RemoveField(
            model_name='transport_booking',
            name='trip_id',
        ),
        migrations.AlterField(
            model_name='place_image',
            name='image_of_place',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Taxi_Booking',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='Transport_Booking',
        ),
    ]
